// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dafsem.Context;

#nullable disable

namespace dafsem.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20241114185603_UpdateAnaSayfaModel")]
    partial class UpdateAnaSayfaModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AfiseIdId")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mektup")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AfiseIdId");

                    b.ToTable("AnaSayfa");
                });

            modelBuilder.Entity("dafsem.Models.FotoGruplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FotoGruplar");
                });

            modelBuilder.Entity("dafsem.Models.Fotolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnaSayfaId")
                        .HasColumnType("int");

                    b.Property<int>("FotoGrupIdId")
                        .HasColumnType("int");

                    b.Property<string>("Yol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnaSayfaId");

                    b.HasIndex("FotoGrupIdId");

                    b.ToTable("Fotolar");
                });

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.HasOne("dafsem.Models.Fotolar", "AfiseId")
                        .WithMany()
                        .HasForeignKey("AfiseIdId");

                    b.Navigation("AfiseId");
                });

            modelBuilder.Entity("dafsem.Models.Fotolar", b =>
                {
                    b.HasOne("dafsem.Models.AnaSayfa", null)
                        .WithMany("Sliderler")
                        .HasForeignKey("AnaSayfaId");

                    b.HasOne("dafsem.Models.FotoGruplar", "FotoGrupId")
                        .WithMany()
                        .HasForeignKey("FotoGrupIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FotoGrupId");
                });

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.Navigation("Sliderler");
                });
#pragma warning restore 612, 618
        }
    }
}
