// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dafsem.Context;

#nullable disable

namespace dafsem.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20241117051738_RemoveFotoGroup")]
    partial class RemoveFotoGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AfiseIdId")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mektup")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AfiseIdId");

                    b.ToTable("AnaSayfa");
                });

            modelBuilder.Entity("dafsem.Models.Fotolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnaSayfaId")
                        .HasColumnType("int");

                    b.Property<string>("Yol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnaSayfaId");

                    b.ToTable("Fotolar");
                });

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.HasOne("dafsem.Models.Fotolar", "AfiseId")
                        .WithMany()
                        .HasForeignKey("AfiseIdId");

                    b.Navigation("AfiseId");
                });

            modelBuilder.Entity("dafsem.Models.Fotolar", b =>
                {
                    b.HasOne("dafsem.Models.AnaSayfa", null)
                        .WithMany("Sliderler")
                        .HasForeignKey("AnaSayfaId");
                });

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.Navigation("Sliderler");
                });
#pragma warning restore 612, 618
        }
    }
}
