// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dafsem.Context;

#nullable disable

namespace dafsem.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20250223194253_IletisimDilTest")]
    partial class IletisimDilTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dafsem.Models.AltSayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltSayfaBaslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UstSayfaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UstSayfaId");

                    b.ToTable("AltSayfa");
                });

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AfiseIdId")
                        .HasColumnType("int");

                    b.Property<string>("Mektup")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.HasIndex("AfiseIdId");

                    b.ToTable("AnaSayfa");
                });

            modelBuilder.Entity("dafsem.Models.Ayarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FiligranId")
                        .HasColumnType("int");

                    b.Property<string>("KurumAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Program")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SagLogoId")
                        .HasColumnType("int");

                    b.Property<string>("SiteAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SiteAltBaslik")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SiteArkaplaniId")
                        .HasColumnType("int");

                    b.Property<int?>("SiteLogoId")
                        .HasColumnType("int");

                    b.Property<int?>("SolLogoId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.HasIndex("FiligranId");

                    b.HasIndex("SagLogoId");

                    b.HasIndex("SiteArkaplaniId");

                    b.HasIndex("SiteLogoId");

                    b.HasIndex("SolLogoId");

                    b.ToTable("Ayarlar");
                });

            modelBuilder.Entity("dafsem.Models.BankaBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<string>("HesapSahibiAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("BankaBilgileri");
                });

            modelBuilder.Entity("dafsem.Models.Basliklar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("Basliklar");
                });

            modelBuilder.Entity("dafsem.Models.Basvuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltMetin")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.Property<string>("UstMetin")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("Basvuru");
                });

            modelBuilder.Entity("dafsem.Models.Dil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DilAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DilKodu")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.ToTable("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Fotolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnaSayfaId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.Property<string>("Yol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnaSayfaId");

                    b.ToTable("Fotolar");
                });

            modelBuilder.Entity("dafsem.Models.HizmetTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("HizmetTuru");
                });

            modelBuilder.Entity("dafsem.Models.Hizmetler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<string>("Hizmet")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasColumnName("Hizmet");

                    b.Property<int>("HizmetTuruId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("HizmetTuruId");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("dafsem.Models.Iletisim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("Iletisim");
                });

            modelBuilder.Entity("dafsem.Models.Konaklama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("KahvaltiDahilMi")
                        .HasColumnType("bit");

                    b.Property<string>("KonaklamaEvi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("Tel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WebSitesi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("YildizSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("Konaklama");
                });

            modelBuilder.Entity("dafsem.Models.KuralTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<int?>("SayfaId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("SayfaId");

                    b.ToTable("KuralTuru");
                });

            modelBuilder.Entity("dafsem.Models.Kurallar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.Property<int>("KuralTuruId")
                        .HasColumnType("int");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("KuralTuruId");

                    b.ToTable("Kurallar");
                });

            modelBuilder.Entity("dafsem.Models.KurulKategorileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<int>("SayfaId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("SayfaId");

                    b.ToTable("KurulKategorileri");
                });

            modelBuilder.Entity("dafsem.Models.KurulUyeleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<int>("KategoriIdId")
                        .HasColumnType("int");

                    b.Property<string>("Kurum")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.Property<int?>("UnvanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("KategoriIdId");

                    b.HasIndex("UnvanId");

                    b.ToTable("KurulUyeleri");
                });

            modelBuilder.Entity("dafsem.Models.OdaTipleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<int>("KonaklamaEviId")
                        .HasColumnType("int");

                    b.Property<string>("OdaTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<float?>("Ucret")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("DilId");

                    b.HasIndex("KonaklamaEviId");

                    b.ToTable("OdaTipleri");
                });

            modelBuilder.Entity("dafsem.Models.ParaBirimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Sembol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("ParaBirimleri");
                });

            modelBuilder.Entity("dafsem.Models.Sayfalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AyarlarId")
                        .HasColumnType("int");

                    b.Property<string>("SayfaBasligi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AyarlarId");

                    b.ToTable("Sayfalar");
                });

            modelBuilder.Entity("dafsem.Models.Tarihler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("Tarihler");
                });

            modelBuilder.Entity("dafsem.Models.Telefonlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dahili")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<int>("IletisimId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("State");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("IletisimId");

                    b.ToTable("Telefonlar");
                });

            modelBuilder.Entity("dafsem.Models.Ucretler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<float>("Ucret")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("DilId");

                    b.ToTable("Ucretler");
                });

            modelBuilder.Entity("dafsem.Models.Unvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DilId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("UnvanAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.ToTable("Unvan");
                });

            modelBuilder.Entity("dafsem.Models.AltSayfa", b =>
                {
                    b.HasOne("dafsem.Models.Sayfalar", "UstSayfa")
                        .WithMany("AltSayfalari")
                        .HasForeignKey("UstSayfaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UstSayfa");
                });

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.HasOne("dafsem.Models.Fotolar", "AfiseId")
                        .WithMany()
                        .HasForeignKey("AfiseIdId");

                    b.Navigation("AfiseId");
                });

            modelBuilder.Entity("dafsem.Models.Ayarlar", b =>
                {
                    b.HasOne("dafsem.Models.Fotolar", "Filigran")
                        .WithMany()
                        .HasForeignKey("FiligranId");

                    b.HasOne("dafsem.Models.Fotolar", "SagLogo")
                        .WithMany()
                        .HasForeignKey("SagLogoId");

                    b.HasOne("dafsem.Models.Fotolar", "SiteArkaplani")
                        .WithMany()
                        .HasForeignKey("SiteArkaplaniId");

                    b.HasOne("dafsem.Models.Fotolar", "SiteLogo")
                        .WithMany()
                        .HasForeignKey("SiteLogoId");

                    b.HasOne("dafsem.Models.Fotolar", "SolLogo")
                        .WithMany()
                        .HasForeignKey("SolLogoId");

                    b.Navigation("Filigran");

                    b.Navigation("SagLogo");

                    b.Navigation("SiteArkaplani");

                    b.Navigation("SiteLogo");

                    b.Navigation("SolLogo");
                });

            modelBuilder.Entity("dafsem.Models.BankaBilgileri", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Basliklar", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Basvuru", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Fotolar", b =>
                {
                    b.HasOne("dafsem.Models.AnaSayfa", null)
                        .WithMany("Sliderler")
                        .HasForeignKey("AnaSayfaId");
                });

            modelBuilder.Entity("dafsem.Models.HizmetTuru", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Hizmetler", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.HasOne("dafsem.Models.HizmetTuru", "Turu")
                        .WithMany()
                        .HasForeignKey("HizmetTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Turu");
                });

            modelBuilder.Entity("dafsem.Models.Iletisim", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Konaklama", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.KuralTuru", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.HasOne("dafsem.Models.AltSayfa", "Sayfa")
                        .WithMany()
                        .HasForeignKey("SayfaId");

                    b.Navigation("Dil");

                    b.Navigation("Sayfa");
                });

            modelBuilder.Entity("dafsem.Models.Kurallar", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dafsem.Models.KuralTuru", "Turu")
                        .WithMany()
                        .HasForeignKey("KuralTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Turu");
                });

            modelBuilder.Entity("dafsem.Models.KurulKategorileri", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.HasOne("dafsem.Models.AltSayfa", "Sayfa")
                        .WithMany()
                        .HasForeignKey("SayfaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Sayfa");
                });

            modelBuilder.Entity("dafsem.Models.KurulUyeleri", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.HasOne("dafsem.Models.KurulKategorileri", "KategoriId")
                        .WithMany("KurulUyeleri")
                        .HasForeignKey("KategoriIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dafsem.Models.Unvan", "Unvan")
                        .WithMany()
                        .HasForeignKey("UnvanId");

                    b.Navigation("Dil");

                    b.Navigation("KategoriId");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("dafsem.Models.OdaTipleri", b =>
                {
                    b.HasOne("dafsem.Models.ParaBirimi", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.HasOne("dafsem.Models.Konaklama", "KonaklamaEvi")
                        .WithMany("Odalar")
                        .HasForeignKey("KonaklamaEviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("Dil");

                    b.Navigation("KonaklamaEvi");
                });

            modelBuilder.Entity("dafsem.Models.ParaBirimi", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Sayfalar", b =>
                {
                    b.HasOne("dafsem.Models.Ayarlar", null)
                        .WithMany("Sayfalar")
                        .HasForeignKey("AyarlarId");
                });

            modelBuilder.Entity("dafsem.Models.Tarihler", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Telefonlar", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.HasOne("dafsem.Models.Iletisim", "Iletisim")
                        .WithMany("Telefonlar")
                        .HasForeignKey("IletisimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Iletisim");
                });

            modelBuilder.Entity("dafsem.Models.Ucretler", b =>
                {
                    b.HasOne("dafsem.Models.ParaBirimi", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.Navigation("Birim");

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.Unvan", b =>
                {
                    b.HasOne("dafsem.Models.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId");

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("dafsem.Models.AnaSayfa", b =>
                {
                    b.Navigation("Sliderler");
                });

            modelBuilder.Entity("dafsem.Models.Ayarlar", b =>
                {
                    b.Navigation("Sayfalar");
                });

            modelBuilder.Entity("dafsem.Models.Iletisim", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("dafsem.Models.Konaklama", b =>
                {
                    b.Navigation("Odalar");
                });

            modelBuilder.Entity("dafsem.Models.KurulKategorileri", b =>
                {
                    b.Navigation("KurulUyeleri");
                });

            modelBuilder.Entity("dafsem.Models.Sayfalar", b =>
                {
                    b.Navigation("AltSayfalari");
                });
#pragma warning restore 612, 618
        }
    }
}
